export const LOCKING_DOC_MENU = 'LOCKING_DOC_MENU';
export const TOGGLE_DOC_MENU = 'TOGGLE_DOC_MENU';
export const LOCKING_USER_MENU = 'LOCKING_USER_MENU';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const CHANGE_CONTAINER_TYPE = 'CHANGE_CONTAINER_TYPE';