export const LOCKING_MENU = 'LOCKING_MENU';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const TOGGLE_LAYER_CONTAINER_DISPLAY = 'TOGGLE_LAYER_CONTAINER_DISPLAY';
export const VERSION_NUMBER = 'VERSION_NUMBER';
export const USER_MESSAGE = 'USER_MESSAGE';
export const DOCUMENT_MESSAGE = 'DOCUMENT_MESSAGE';